backend:
  name: github
  branch: develop # Branch where CMS changes will be committed
  repo: aubskate/classics # Path to your GitLab repository
  use_large_media_transforms_in_media_library: false
media_folder: "src/assets/videos" # Media files will be stored in the repo under images/uploads
public_folder: "/assets/videos"

collections:
  - name: "home"
    label: "Home"
    folder: "src/content/home"
    fields:
      - name: "name"
        widget: "string"
        required: true
      - label: "Featured Image"
        name: "hero"
        widget: "image"
        required: false
      - label: "Featured Title"
        name: "title"
        widget: "string"
        required: false
      - label: "Feature Description"
        name: "markdown"
        widget: "string"
        required: false
      - label: "Body"
        name: "content"
        widget: "markdown"
        required: false
      - label: "Tags"
        name: "tags"
        widget: "hidden"
        default: "home"
  - name: "video"
    label: "Videos"
    folder: "src/content/video"
    fields:
      - name: "name"
        widget: "string"
        required: true
      - name: "year"
        widget: "string"
        required: false
      - label: "Body"
        name: "content"
        widget: "markdown"
        required: false
      - label: "Tags"
        name: "tags"
        widget: "hidden"
        default: "video"
