backend:
  name: github
  branch: staging # Branch where CMS changes will be committed
  repo: aubskate/classics # Path to your GitLab repository
  use_large_media_transforms_in_media_library: false
media_folder: "src/assets/videos" # Media files will be stored in the repo under images/uploads
public_folder: "/assets/videos"

collections:
  - name: "home"
    label: "Home"
    folder: "src/content/home"
    fields:
      - name: "name"
        widget: "string"
        required: true
      - label: "Featured Image"
        name: "hero"
        widget: "image"
        required: false
      - label: "Featured Title"
        name: "title"
        widget: "string"
        required: false
      - label: "Feature Description"
        name: "markdown"
        widget: "string"
        required: false
      - label: "Body"
        name: "content"
        widget: "markdown"
        required: false
      - label: "Tags"
        name: "tags"
        widget: "hidden"
        default: "home"
  - name: "video"
    label: "Video"
    folder: "src/content/video"
    create: true
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
        required: true
      - label: "Slug"
        name: "slug"
        widget: "string"
        required: true
      - label: "Year"
        name: "year"
        widget: "string"
        required: true
      - label: "Released"
        name: "released"
        widget: "date"
        required: true
      - label: "Produced By"
        name: "production"
        widget: "string"
        required: true
      - label: "Video"
        name: "file"
        widget: "file"
        required: false
      - label: "External Streaming URL"
        name: "streaming"
        widget: "string"
        required: false
      - label: "Use External"
        name: "external"
        widget: "boolean"
        default: true
        required: false
      - label: "Image"
        name: "poster"
        widget: "image"
        required: true
      - label: "Download Link"
        name: "download"
        widget: "string"
        required: true
      - label: "Body"
        name: "content"
        widget: "markdown"
        required: false
      - label: "Tags"
        name: "tags"
        widget: "hidden"
        default: "video"
